### ISSUE TITLE
Cannot Change Texture Resolution In Blender. 

### ISSUE THREAD

**Issue by dankasaurosrex** [Poly-Haven/polyhavenassets#108]
**Describe the bug**
I honestly have no idea what's going on. I cannot change the resolution to any of my textures. I have deleted blender, reinstalled it, restarted my computer, deleted the add on, reinstalled it, followed the proper download instructions multiple times, and for some reason I still cannot increase the resolution of the textures. What has happened on some occasions is I will begin blender and on a blank project it will actually sometimes allow me to download higher res texture. The moment I go to the project I want to work on, or if I begin adding to the new project, my ability to increase res once again disappears. I have tried more than what I have listed and I honestly don't know what to do. The following is the error message I receive on blender each time I attempt to increase the resolution:

PASTE CONSOLE OUTPUT HERE
Last login: Thu Apr 11 16:07:05 on ttys000
andonihollenbeck@Andonis-MacBook-Pro ~ % cd /Applications/Blender.app/Contents/MacOS
./Blender
Read prefs: "/Users/andonihollenbeck/Library/Application Support/Blender/4.1/config/userpref.blend"
Read blend: "/var/folders/33/m6990fr143bc2_2kl_t6g7140000gn/T/4024_autosave.blend"
RNA_boolean_set: OBJECT_OT_drop_named_material.show_datablock_in_modifier not found.
Traceback (most recent call last):
  File "/Users/andonihollenbeck/Library/Application Support/Blender/4.1/scripts/addons/polyhavenassets/operators/resolution_switch.py", line 170, in execute
    images_exist.append(update_image(img, self.asset_id, self.res, lib_path, info, dry_run=True))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andonihollenbeck/Library/Application Support/Blender/4.1/scripts/addons/polyhavenassets/operators/resolution_switch.py", line 53, in update_image
    rel_path = abspath(img.filepath).relative_to(lib_path.resolve() / asset_id).as_posix()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/private/Users/andonihollenbeck/Documents/Poly Haven/aerial_beach_03/textures/aerial_beach_03_disp_1k.png' is not in the subpath of '/Users/andonihollenbeck/Documents/Poly Haven/aerial_beach_03' OR one path is relative and the other is absolute.
Error: Python: Traceback (most recent call last):
  File "/Users/andonihollenbeck/Library/Application Support/Blender/4.1/scripts/addons/polyhavenassets/operators/resolution_switch.py", line 170, in execute
    images_exist.append(update_image(img, self.asset_id, self.res, lib_path, info, dry_run=True))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andonihollenbeck/Library/Application Support/Blender/4.1/scripts/addons/polyhavenassets/operators/resolution_switch.py", line 53, in update_image
    rel_path = abspath(img.filepath).relative_to(lib_path.resolve() / asset_id).as_posix()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/private/Users/andonihollenbeck/Documents/Poly Haven/aerial_beach_03/textures/aerial_beach_03_disp_1k.png' is not in the subpath of '/Users/andonihollenbeck/Documents/Poly Haven/aerial_beach_03' OR one path is relative and the other is absolute.

Here is also a screenshot of the error code I receive:
<img width="1728" alt="Screenshot 2024-04-10 at 10 53 54 PM" src="https://github.com/Poly-Haven/polyhavenassets/assets/166764884/61fc1569-59c1-4513-9881-54a9f7c02851">

Any help is deeply appreciated. Thank you so much!

**Comment by gregzaal** [comment]
Hey there, can you try updating the add-on from your preferences? There was a similar issue fixed back in 1.0.3.

**Comment by dankasaurosrex** [comment]
Hello! Unfortunately I already tried to update it but it said I was up to date

**Comment by gregzaal** [comment]
What version does it say the add-on is installed in the preferences?

**Comment by gregzaal** [comment]
And in case I don't reply over the weekend, you can try deleting the folder for your asset library, and redownloading everything again (click fetch assets).
