### ISSUE TITLE
Error upon enabling the add-on

### ISSUE THREAD

**Issue by mls3000** [Poly-Haven/polyhavenassets#113]
Installing version 1.1.7 of the addon on Blender 4.1.0, macOS Sonoma 14.4.1 (MacStudio 2022, Apple M1 Max), I get the following error output when activating:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'polyhavenassets-1'
```

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
