### ISSUE TITLE
Error opon Fetch Assets

### ISSUE THREAD

**Issue by bax64** [Poly-Haven/polyhavenassets#114]
Hey, I get this error when trying to Fetch Assets.

Python: Traceback (most recent call last):
  File "C:\Users\basti\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 299, in execute
    error, assets = get_asset_list(self.asset_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\basti\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
