### ISSUE TITLE
Maintain functionality even after blend file/library is moved

### ISSUE THREAD

**Issue by gregzaal** [Poly-Haven/polyhavenassets#115]
Right now we use `asset.library_weak_reference` to get the path and determine if a datablock is an asset or not. This is not entirely always reliable and can cause strange behavior especially when the blend file or library itself is relocated.

Perhaps there's a better way to keep track of our assets (e.g. custom property) and maintain the ability to do things like resolution switching even after the user has moved their library or when the current file was moved in the OS and relative paths are no longer correct.

**Comment by trailofsevens** [comment]
Currently running into this issue with Poly Haven assets (latest version) - I'm using Syncthing to sync my project files and assets folders between a desktop and laptop. My desktop folder structure is:
D:\assets\poly haven\
D:\assets\textures\
D:\projects\projectname\

Unfortunately the laptop only has 1 SSD so it's folder structure can't be duplicated on a D drive: 
C:\Users\Name\assets\poly haven\
C:\Users\Name\assets\textures\
C:\Users\Name\projects\projectname\

Blender's relative paths handle this no problem when I manually add files from \assets\textures\. Polyhaven is inconsistent, I tested: 
- Create file on desktop: add a polyhaven texture, save, sync. 
- Open on laptop: relative paths work, save, sync.
- Open on desktop: relative paths work, change resolution of texture, save, sync.
- Open on laptop: the texture is missing and then even if I try to change it back to the previous resolution (or any resolution) I get the following:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender\blender-4.3.2\portable\scripts\addons\polyhavenassets\operators\resolution_switch.py", line 170, in execute
    images_exist.append(update_image(img, self.asset_id, self.res, lib_path, info, dry_run=True))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender\blender-4.3.2\portable\scripts\addons\polyhavenassets\operators\resolution_switch.py", line 53, in update_image
    rel_path = abspath(img.filepath).relative_to(lib_path.resolve() / asset_id).as_posix()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender\blender-4.3.2\4.3\python\Lib\pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'D:\\assets\\poly haven\\brick_wall_04\\textures\\brick_wall_04_diff_4k.jpg' is not in the subpath of 'C:\\Users\\Matt\\assets\\poly haven\\brick_wall_04' OR one path is relative and the other is absolute.
```

Excuse any over-explaining of an issue already on your radar, just being thorough in case anyone else lands here too (like I did when Googling this),
