### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by CoolData101** [Poly-Haven/polyhavenassets#116]
**Describe the bug**
Hello im new to poly haven and whenever I try to get the assets,HDris or anything other than the main page it doesn't like it and just spits this error. I tried three other browsers all resulting in this error 😭 
![Screenshot 2024-05-30 2024711](https://github.com/Poly-Haven/polyhavenassets/assets/64379866/7bf047e2-217c-478b-a3f5-d5aa307a538e)

**Console log from browser **
![Screenshot 2024-05-302 204957](https://github.com/Poly-Haven/polyhavenassets/assets/64379866/898634f7-6b6a-4bc4-b8f3-eac5d41b9db2)

```
PASTE CONSOLE OUTPUT HERE
```

Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ab (framework-aec4381329cec0e4.js:1:61050)
    at ud (framework-aec4381329cec0e4.js:1:72892)
    at i (framework-aec4381329cec0e4.js:1:120446)
    at oO (framework-aec4381329cec0e4.js:1:99198)
    at framework-aec4381329cec0e4.js:1:99065
    at oF (framework-aec4381329cec0e4.js:1:99072)
    at ox (framework-aec4381329cec0e4.js:1:95824)
    at oC (framework-aec4381329cec0e4.js:1:96213)
    at r4 (framework-aec4381329cec0e4.js:1:44867)
    at framework-aec4381329cec0e4.js:1:93716
a5 @ framework-aec4381329cec0e4.js:1
main-af75fc7f4d2f8fc6.js:1 Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ab (framework-aec4381329cec0e4.js:1:61050)
    at ud (framework-aec4381329cec0e4.js:1:72892)
    at i (framework-aec4381329cec0e4.js:1:120446)
    at oO (framework-aec4381329cec0e4.js:1:99198)
    at framework-aec4381329cec0e4.js:1:99065
    at oF (framework-aec4381329cec0e4.js:1:99072)
    at ox (framework-aec4381329cec0e4.js:1:95824)
    at oC (framework-aec4381329cec0e4.js:1:96213)
    at r4 (framework-aec4381329cec0e4.js:1:44867)
    at framework-aec4381329cec0e4.js:1:93716
ee @ main-af75fc7f4d2f8fc6.js:1
main-af75fc7f4d2f8fc6.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ee @ main-af75fc7f4d2f8fc6.js:1
_app-d25e15ce2a51e35b.js:1 react-i18next:: You will need to pass in an i18next instance by using initReactI18next

**Additional context**
Boop :3

**Comment by gregzaal** [comment]
Thanks for the report, the issue was fixed earlier today. If it's still broken for you, try Ctrl-F5 or Shift-F5.
