### ISSUE TITLE
Cannot install add-on

### ISSUE THREAD

**Issue by BramKreuger** [Poly-Haven/polyhavenassets#119]
I cannot "check" the checkmark after downloading the zipfile from the blendermarket:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\sheep\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\polyhavenassets\__init__.py", line 156, in register
    bpy.types.ASSETBROWSER_MT_editor_menus.append(ui.asset_lib_titlebar.ui)
AttributeError: 'RNA_Types' object has no attribute 'ASSETBROWSER_MT_editor_menus'

**Comment by BramKreuger** [comment]
Updating to the newest version of blender fixed this!
