### ISSUE TITLE
Error Fetching Assets for the First Time

### ISSUE THREAD

**Issue by MJRoark** [Poly-Haven/polyhavenassets#38]
Receiving the following error after clicking "Fetch Assets" for the first time. I have tried disabling ssl, restarted blender, and turned off antivirus.

Python: Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 260, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

**Comment by gregzaal** [comment]
Hi,

If you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully - it seems you did not rename the installed folder.
