### ISSUE TITLE
Disable SSL Verify [Blender 3.4]

### ISSUE THREAD

**Issue by d3ddev3** [Poly-Haven/polyhavenassets#47]
Unable to fetch Assets after installation.
Disable SSL Verification ON and OFF trow the same Error.

Python: Traceback (most recent call last):
  File "C:\Users\d3d\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 260, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\d3d\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

**Expected behavior**
Download of all or selected Category

**Comment by gregzaal** [comment]
Hi there, please be sure to follow the installation instructions carefully if downloading from GitHub, you need to rename the install folder to remove the `-main`.

The version on Patreon and the BM is prepackaged to avoid this.
