### ISSUE TITLE
Asset Browser Empty

### ISSUE THREAD

**Issue by nailuj05** [Poly-Haven/polyhavenassets#56]
I have installed the addon like described. It shows up correctly in my preferences aswell. I have added a Asset Library named "Poly Haven" aswell. When I open the asset browser window and select the poly haven library nothing shows up however. 
If I click on fetch assets blender stops responding. 
I am on Fedora Workstation 37 (Gnome) using blender 3.4 from DNF. 

**Console log**
The only console output I get is this:

```$ blender
BLT_lang_init: 'locale' data path for translations not found, continuing
Read prefs: /home/julian/.config/blender/3.4/config/userpref.blend
../src/intel/isl/isl.c:2235: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
```

**Expected behavior**
I would expect the assets/folders structure/previews to show before the fetch/download

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57530068/220886838-e91bd6b8-1b51-4643-a8c3-070dd3c92f4d.png)

![grafik](https://user-images.githubusercontent.com/57530068/220886968-6eee225d-b692-43bf-92d9-95a87252a53f.png)

![grafik](https://user-images.githubusercontent.com/57530068/220887027-dbfb2271-aa83-4318-9b41-67c3768642d3.png)

**Comment by gregzaal** [comment]
I'm afraid without any actual error messages I have absolutely no idea what could be happening here. No other users have made similar reports and I can't reproduce the problem.

**Comment by nailuj05** [comment]
After restarting my system the folder structure is now showing and the thumbnails are in the folders (but not displayed in blender).
Blender still stops responding when clicking on the fetch assets button, however I did get a error message this time when killing the process:
```
Python: Traceback (most recent call last):
  File "/home/julian/.config/blender/3.4/scripts/addons/polyhavenassets/operators/pull_from_polyhaven.py", line 282, in execute
    error, assets = get_asset_list(self.asset_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julian/.config/blender/3.4/scripts/addons/polyhavenassets/utils/get_asset_list.py", line 17, in get_asset_list
    res = requests.get(url, headers=REQ_HEADERS, verify=verify_ssl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

![grafik](https://user-images.githubusercontent.com/57530068/220890847-417c7360-70ac-4681-8465-0bb8a2304900.png)

**Comment by gregzaal** [comment]
Based on those errors there seems to be a connection issue between you and the server. This may be a firewall thing on your side, or any number of potential network related problems that unfortunately I cannot help you debug as everything is working fine on our end. There are a few potential solutions listed on our [troubleshooting page](https://github.com/Poly-Haven/polyhavenassets/wiki/Troubleshooting) that you can start with, but other than that this does not seem to be a bug with our add-on.
