### ISSUE TITLE
Fetch 2416 new assets don't work

### ISSUE THREAD

**Issue by Kryde17** [Poly-Haven/polyhavenassets#62]
**Describe the bug**
Hello, I can't Fetch 2416 new assets

**Console log**
Python : Traceback (most recent call last):
  File "C:\Users\Kryde17\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 291, in execute
    copy_file(default_catalog_file, catalog_file)
  File "C:\Program Files\3D\Blender Foundation\Blender 3.4\3.4\python\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\3D\Blender Foundation\Blender 3.4\3.4\python\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\3D\\Blender Foundation\\Blender 3.4\\Poly Haven\\blender_assets.cats.txt'

**Screenshots**

<img width="960" alt="bug" src="https://user-images.githubusercontent.com/128090170/225729946-3da18bfb-701d-461f-8466-e847a41795d7.png">

**Comment by gregzaal** [comment]
Based on your error message, it looks like you have your asset library set inside a protected folder (Program Files) which Blender does not have access to.

You'll either need to select a different folder (outside of Program Files) for your asset library, or modify your user permissions so that Program Files is accessible by Blender.
