### ISSUE TITLE
HDRI assets error

### ISSUE THREAD

**Issue by flasher69** [Poly-Haven/polyhavenassets#66]
I cannot use any of the HDRI assets. If I want to use a preset, I have to open the original hdri asset file and choose the right hdri image in the shader editor manually and then save. After that, it works fine. I don't have this issue with objects and materials though. I'm using Blender 3.5.1

**Console log**

```
bpy.ops.scatter5.reload_biome_library()
Python: Traceback (most recent call last):
  File "C:\Users\The Crow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets\operators\resolution_switch.py", line 167, in execute
    images_exist.append(update_image(img, self.asset_id, self.res, lib_path, info, dry_run=True))
  File "C:\Users\The Crow\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets\operators\resolution_switch.py", line 52, in update_image
    rel_path = Path(bpy.path.abspath(img.filepath)).resolve().relative_to(lib_path.resolve() / asset_id).as_posix()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'C:\\Users\\thecrow\\Dropbox\\Kurs\\Blender\\Assets\\Poly Haven\\abandoned_factory_canteen_01\\abandoned_factory_canteen_01_1k.hdr' is not in the subpath of 'E:\\Dropbox\\Kurs\\Blender\\Assets\\Poly Haven\\abandoned_factory_canteen_01' OR one path is relative and the other is absolute.

```

![Screenshot 2023-05-05 192649](https://user-images.githubusercontent.com/22278347/236525824-3044045e-c1e1-4f59-adc4-23b5a7450f1a.png)

**Comment by flasher69** [comment]
never mind. I've deleted everything and reinstalled everything and now it works. This post can be closed.
