### ISSUE TITLE
Dysfonction download assets - polyhavenassets not found

### ISSUE THREAD

**Issue by piroule50** [Poly-Haven/polyhavenassets#68]
**Describe the bug**
Installation addon with video https://www.youtube.com/watch?v=ku_xv6WV6UE

**Console log**
Start blender from a command prompt/terminal...

```
C:\Program Files\Blender Foundation\Blender 3.5>blender.exe
Read prefs: C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
register_class(...):
Warning: 'imeshh.settings_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'imeshh.view_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'object.custom_panel' does not contain '_PT_' with prefix and suffix
Exception in thread Thread-1 (check_for_new_assets):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\check_for_new_assets.py", line 13, in check_for_new_assets
    error, assets = get_asset_list()
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Exception in thread Thread-2 (check_for_new_assets):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\check_for_new_assets.py", line 13, in check_for_new_assets
    error, assets = get_asset_list()
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit INFO: Global dir permissions are OK. [09:49:41.955, utils.py:1280]
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
blenderkit INFO: Dependencies are available [09:49:42.244, dependencies.py:111]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000245DE415C00>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [09:49:43.426, timer.py:36]
blenderkit INFO: Daemon server starting on address http://127.0.0.1:62485, log file for errors located at: C:\Users\pijur\blenderkit_data\daemon/daemon-62485.log [09:49:43.487, daemon_lib.py:593]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000245DE5E2110>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [09:49:43.615, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000245DE5E3A60>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [09:49:43.835, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000245DE415C60>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [09:49:44.145, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000245DE5E3520>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [09:49:44.552, timer.py:36]
blenderkit INFO: Daemon is running on port 62485! [09:49:45.209, timer.py:86]
Exception in thread Thread-6 (check_for_new_assets):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\check_for_new_assets.py", line 13, in check_for_new_assets
    error, assets = get_asset_list()
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Traceback (most recent call last):
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 282, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Error: Python: Traceback (most recent call last):
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 282, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\pijur\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to 'Asset browse' and open 'Poly Haven' library who is empty.
2. Click on 'Fetch Assets' and pop-up 'Fetch assets from polyhaven.com
3. Scroll down to '....' : N/A
4. See error : Pop up report: Error... KeyError: key "polyhavenassets" not found

**Expected behavior
I'm looking to load assets

**Screenshots: polyhaven_addon_report error.png

**Additional context: N/A

![polyhaven_addon_report error](https://github.com/Poly-Haven/polyhavenassets/assets/136568769/4427e136-6ba3-4b1e-895f-ed12de647a65)

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
