### ISSUE TITLE
Impossible to enable the plugin on Blender 3.5

### ISSUE THREAD

**Issue by Cinrod** [Poly-Haven/polyhavenassets#72]
Hello,

I'm French so excuse my english. I ordered your fabulous product today. And it looks like not installed.
I checked your support and this issue meens that I do not have a good version of blender.
I have 3.5 so I do not really understand the problem.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
Microsoft Windows [version 10.0.22621.1848]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\matth>
C:\Users\matth>C:\Program Files\Blender Foundation\Blender\blender.exe
'C:\Program' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\matth>"C:\Program Files\Blender Foundation\Blender 3.5\blender.exe"
Read prefs: C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\3Points_Align\__init__.py", line 12, in <module>
    from .operators import THREE_POINTS_ALIGN_OT_check_selection, THREE_POINTS_ALIGN_OT_align
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\3Points_Align\operators.py", line 6, in <module>
    from .core import RAY_CAST, PARAM_UI, DRAW, LINE, MARK
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\3Points_Align\core.py", line 2, in <module>
    from bpy.types import SAFE_AREAS_PT_presets
ImportError: cannot import name 'SAFE_AREAS_PT_presets' from 'bpy.types' (unknown location)
botaniq install dir autodetected as C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\botaniq_full (big zip embedded)
Photographer requires Cycles to operate, automatically enabling it...
Cycles is now enabled.
Exception in module register(): C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photographer\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photographer\__init__.py", line 365, in register
    library.register()
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photographer\ui\library.py", line 396, in register
    list_subfolders()
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\photographer\ui\library.py", line 92, in list_subfolders
    subfolders = [ f.path for f in os.scandir(folder) if f.is_dir() ]
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\matth\\Desktop\\BORGNET_PROD\\Expo_Scene\\in\\HDRI\\'
Exception in module unregister(): 'C:\\Program Files\\Blender Foundation\\Blender 3.5\\3.5\\scripts\\addons\\cycles\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 295, in enable
    mod.unregister()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\cycles\__init__.py", line 159, in unregister
    ui.unregister()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\addons\cycles\ui.py", line 2512, in unregister
    unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

----------------------------------------------

No module named 'blenderbim'
Archipack ifc export fallback
Archipack PRO 2.6.0 : ready

----------------------------------------------

blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029EC0A73CD0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [11:25:45.591, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029EC0A734C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [11:25:49.513, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029EC0A72D40>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [11:25:49.724, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029EC0AADD50>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [11:25:50.024, timer.py:36]


```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to Edit > "preferences"
2. Click on 'addon
3. Click on Install
4. Select the .zip file : "polyhavenassets_blendermarket.zip"
5. The plugin is installed
6. clic on clic box to enabled the plugin line"import-export : Poly Haven Assets"
7. Appears a issue message into the console :
```
Exception in module register(): C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\matth\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\polyhavenassets\__init__.py", line 110, in register
    register_class(cls)
RuntimeError: Error: Registering panel class: parent 'CYCLES_PT_context_material' for 'PHA_PT_asset_model_cycles' not found
```

**Expected behavior**
I want to be able to use my plugin ordered

**Screenshots**
![image](https://github.com/Poly-Haven/polyhavenassets/assets/137882065/fdddb7b9-906c-4814-924d-67d5d459ca53)

Thanks for your help!

**Comment by gregzaal** [comment]
Hi again :)

From that console log there doesn't seem to be any issues with our add-on printed, but I see there is another add-on, "Photographer", which is manipulating other add-ons and having issues itself.

Can you try launch Blender from factory defaults (`"C:\Program Files\Blender Foundation\Blender 3.5\blender.exe" --factory-startup`) and see if the issue persists? It's possible that that add-on (or another one) is preventing ours from being activated.
