### ISSUE TITLE
Plugin won't download new assets.

### ISSUE THREAD

**Issue by MichaelRColton** [Poly-Haven/polyhavenassets#79]
**Describe the bug**
The Poly Haven asset browser plugin isn't downloading new assets.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
C:\Program Files\Blender Foundation\Blender 3.6>blender.exe
Read prefs: "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Warning: Unable to read 'C:\tmp\phassetlib\patterned_cobblestone\patterned_cobblestone.blend': insufficient content
Warning: Unable to read 'C:\tmp\phassetlib\pavement_01\pavement_01.blend': insufficient content
Warning: Unable to read 'C:\tmp\phassetlib\patterned_cobblestone\patterned_cobblestone.blend': insufficient content
Warning: Unable to read 'C:\tmp\phassetlib\pavement_01\pavement_01.blend': insufficient content
Exception in thread Thread-4 (long_task):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 233, in long_task
    error, exists = update_asset(
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 40, in update_asset
    old_info = json.load(f)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Info: Downloaded 0 assets

Warning: Unable to read 'C:\tmp\phassetlib\patterned_cobblestone\patterned_cobblestone.blend': insufficient content
Warning: Unable to read 'C:\tmp\phassetlib\pavement_01\pavement_01.blend': insufficient content
Exception in thread Thread-5 (long_task):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 233, in long_task
    error, exists = update_asset(
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 40, in update_asset
    old_info = json.load(f)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Info: Downloaded 0 assets

Warning: Unable to read 'C:\tmp\phassetlib\patterned_cobblestone\patterned_cobblestone.blend': insufficient content
Warning: Unable to read 'C:\tmp\phassetlib\pavement_01\pavement_01.blend': insufficient content
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to Asset Browser
2. Select "Poly Haven" from the drop down. "Fetch 538 new assets" button appears
3. Click it
4. Confirm "Fetch assets from Poly Haven, Okay?"
5. See "Downloading in background..." followed by "Downloaded 0 assets"

**Expected behavior**
New assets should be downloaded (or if they can't be, an error should be reported)

**Screenshots**
Probably not helpful

**Additional context**
Blender 3.6, using plugin 1.1.3 downloaded from Patreon supporter page.

**Comment by gregzaal** [comment]
I see a few errors there:

```
Warning: Unable to read 'C:\tmp\phassetlib\pavement_01\pavement_01.blend': insufficient content
...
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

There are multiple files that Blender is unable to read or decode, so it seems like your library folder has been corrupted somehow. Could you delete the entire library folder and try again? If there was a different error that caused the corruption, you might be able to see this by running Blender from the command prompt again after deleting the library.

**Comment by MichaelRColton** [comment]
Purging my asset library does seem to have gotten things working again.

I was able to download some assets before this issue popped up before, I'll come back if it happens again. I was low on disk space at the time (though I don't believe I ever ran out completely), so maybe there's something to that.

Not sure how often this happens, but it would be cool if the plugin would detect and handle corrupted files (delete, or delete and redownload), or at least inform the user.

Thanks for your help!

**Comment by gregzaal** [comment]
Thanks Michael. Yes it should be possible to detect this corruption case, I'll make a note to add it in the next release. Feel free to reply here if you run into any more issues like this 👍
