### ISSUE TITLE
Python Fetch Assets error

### ISSUE THREAD

**Issue by spookyblock** [Poly-Haven/polyhavenassets#82]
Fetch assets is not working

```
Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 294, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

```
Python: Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets\operators\pull_from_polyhaven.py", line 303, in execute
    copy_file(default_catalog_file, catalog_file)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Poly Haven\\polyhavenassets\\blender_assets.cats.txt'

Followed all instructions tried to change file location and reinstall but nothing works.

**Comment by spookyblock** [comment]
Nevermind I was able to make it work by running as administrator on Windows 11 if anyone else encounters issues with trying to fetch assets
