### ISSUE TITLE
Cant start fetching assets

### ISSUE THREAD

**Issue by MitchelLeg** [Poly-Haven/polyhavenassets#90]
**Describe the bug**
After pressing Fetch assets i got error about code and nothing heppen.

**Console log**
console output here:

```
Read prefs: "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Exception in thread Thread-1 (check_for_new_assets):
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\check_for_new_assets.py", line 13, in check_for_new_assets
    error, assets = get_asset_list()
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Exception in thread Thread-2 (check_for_new_assets):
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\check_for_new_assets.py", line 13, in check_for_new_assets
    error, assets = get_asset_list()
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Traceback (most recent call last):
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 294, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
Error: Python: Traceback (most recent call last):
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 294, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\ilukr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to "Asset browser" (Shift+f1)
2. Choose "Poly Haven" library
3. Press "Fetch Assets" button.

**Expected behavior**
Expected starting of background download assets.

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
