### ISSUE TITLE
still errors with  fetch assets

### ISSUE THREAD

**Issue by mcbride19** [Poly-Haven/polyhavenassets#97]
**Describe the bug**
after click on " fetch assets on polyhaven" there  is an error
Add-on installed correctly following the instructions !!!!

```
Python: Traceback (most recent call last):
  File "C:\Users\mcbride-pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 294, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\mcbride-pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'

```

**Comment by daHawkz0r** [comment]
Still with the bug. Can not fetch the assets.

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.

**Comment by mcbride19** [comment]
Stop saying to follow the instructions, I followed perfectly the instructions, try to admit that there can be problems on some machines(as I can see I'm not the only one) !!!
 after click on " fetch assets on polyhaven" there is an error
**Add-on installed correctly following the instructions** !!!!

Python: Traceback (most recent call last):
  File "C:\Users\mcbride-pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\polyhavenassets-main\operators\pull_from_polyhaven.py", line 294, in execute
    error, assets = get_asset_list(self.asset_type)
  File "C:\Users\mcbride-pc\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\polyhavenassets-main\utils\get_asset_list.py", line 15, in get_asset_list
    verify_ssl = not bpy.context.preferences.addons["polyhavenassets"].preferences.disable_ssl_verify
KeyError: 'bpy_prop_collection[key]: key "polyhavenassets" not found'
